### ISSUE TITLE
dnsmap not in Debian despite the references

### ISSUE THREAD

**Issue by eribertomota** [resurrecting-open-source-projects/dnsmap#1]
There are some references to Debian Project and 'apt-get install dnsmap' in README.md and CONTRIBUTING.md. However, the dnsmap is not in Debian...

...not yet, but it will arrive to Debian soon! It is confirmed.

**Comment by thiagoandrade01** [comment]
dnsmap is already in Debian. Thank you for maintaining the project.

**Comment by eribertomota** [comment]
Thanks a lot!
